---
title: "Seminar3"
author: "Jianghong Man"
date: "01/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data(faithful)
head(faithful)
```

```{r}
dim(faithful)
```

```{r}
plot(density(faithful$eruptions))
```

```{r}
plot(density(faithful$waiting))
```

```{r}
library(MASS)
head(geyser)
```

```{r}
dim(geyser)
```

```{r}
plot(density(geyser$waiting))
```

```{r}
plot(density(as.numeric(geyser$duration)))
```

```{r}
plot(geyser)
```

```{r}
mixDensity<-function(x,paramVec){
    alpha <- paramVec[1] 
    mu_1 <- paramVec[2] 
    mu_2 <- paramVec[3] 
    sigma_1 <- paramVec[4]  
    sigma_2 <- paramVec[5]
    Density <- alpha * dnorm(x,mu_1,sigma_1) + (1-alpha) * dnorm(x,mu_2,sigma_2) 
    return(Density)
}

mixLogLikeli<-function(paramVec,Sample){
  alpha <- paramVec[1] 
  mu_1 <- paramVec[2] 
  mu_2 <- paramVec[3] 
  sigma_1 <- paramVec[4]  
  sigma_2 <- paramVec[5]
  mll <- -sum(log((alpha * dnorm(x = Sample, mean = mu_1, sd = sigma_1) + (1-alpha)*dnorm(x=Sample, mean = mu_2, sd = sigma_2))))
  return(mll)
}
```

```{r}
var(faithful$eruptions)
```

```{r}
mean(faithful$eruptions)
```

```{r}
Neg_Log_Like_optim<-optim(c(0.5,3.5,3.5,1.3,1.3),
                          mixLogLikeli,
                          Sample = faithful$eruptions,
                          method="L-BFGS-B",
                          hessian=TRUE,
                          lower=c(-Inf,0),
                          control=list(trace=1))
```

```{r}
Neg_Log_Like_optim$par
```

```{r}
Neg_Log_Like_optim$hessian
```

```{r}
# fisher 
Neg_Log_Like_optim$hessian[4,5]
```
