---
title: "Workshop1"
author: "Jianghong Man"
date: "01/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prepare the Data

```{r}
dataPath <- "/Users/nimo/Desktop/31010/1/Workshop/"
Linear.Model.Data <- read.csv(file=paste(dataPath,"Week1ProjectData.csv",sep="/"),
                              header=TRUE,sep=",")
Linear.Model.Data[1:10,]
```

```{r}
Linear.Model.Data.Frame <- as.data.frame(Linear.Model.Data)
```

# Fit Linear model Using lm() and glm()

```{r}
# Estimate the model using lm() and glm()
Linear.Model.Data.lm <- lm(Output~Input, data=Linear.Model.Data.Frame)
Linear.Model.Data.glm <- glm(Output~Input,family=gaussian(link="identity"),
                             data=Linear.Model.Data.Frame)
```

```{r}
# Check and compare the names of the objects elements in both fits.
names(Linear.Model.Data.lm)
```

```{r}
names(Linear.Model.Data.glm)
```

```{r}
# Compare the summaries of outputs.
summary(Linear.Model.Data.lm)
```

```{r}
summary(Linear.Model.Data.glm)
```

# Compare the Model Objects.

## 1. Coefficients.

```{r}
# Come from both functions and have the same meaning and values.

# Coefficients
cbind(Output.LM=Linear.Model.Data.lm$coefficients,Output.GLM=Linear.Model.Data.glm$coefficients)
```

## 2. Residuals.

```{r}
# In the case of Gaussian linear model maximization of log-likelihood is equivalent to minimization of SSE. This should result in the same values for the residuals of lm() as those of glm().

# Residuals
cbind(Output.LM=Linear.Model.Data.lm$residuals,Output.GLM=Linear.Model.Data.glm$residuals)[1:10,]
```

```{r}
# This comparison tells us that the values of residuals from lm() are not identical to residuals from glm(). But this is a result of two different numerical methods used by the functions: maximum log-likelihood in glm() vs. minimum least squares in lm().
(Linear.Model.Data.lm$residuals==Linear.Model.Data.glm$residuals)[1:10]
```

```{r}
# Make a more meaningful comparison:
sum(abs(Linear.Model.Data.lm$residuals-Linear.Model.Data.glm$residuals)>.00000000001)
```

```{r}
# We will later distinguish several definitions of residuals which will not be equivalent in case of generalized linear model. But for the case of Gaussian linear model they are the same:

# Types of residuals
Different.Residuals<-cbind(Linear.Model.Data.lm$residuals,
                           resid(Linear.Model.Data.glm,type="deviance"),
                           resid(Linear.Model.Data.glm,type="pearson"),
                           resid(Linear.Model.Data.glm,type="working"),
                           resid(Linear.Model.Data.glm,type="response"),
                           Linear.Model.Data.glm$residuals)
Different.Residuals[1:10,]
```

```{r}
# Calculate sums of absolute differences between all types of residuals and Linear.Model.Data.lm$residuals to see that they are practically identical.
apply(Different.Residuals[,-1],2,function(column.vector) sum(abs(column.vector-Different.Residuals[,1])))
```

## 3. Fitted values.
 
```{r}
# Check that in the case of Gaussian linear model there is no difference between the returned fitted values.

# Fitted values
(Linear.Model.Data.lm$fitted.values==Linear.Model.Data.glm$fitted.values)[1:10]
```

```{r}
# Again, but: 
sum(abs(Linear.Model.Data.lm$fitted.values-Linear.Model.Data.glm$fitted.values))
```

## 4. Linear predictors.

```{r}
sum(abs(Linear.Model.Data.lm$fitted.values-Linear.Model.Data.glm$linear.predictors))
```

## 5. Deviance.

```{r}
# Check that in the case of Gaussian linear model deviance is equivalent to the sum of squares of errors (SSE).
# Calculate deviance using deviance() and manually and compare with Linear.Model.Data.glm$deviance:

# SSE vs. Deviance
c(From.GLM=Linear.Model.Data.glm$deviance,
  From.LM=sum(Linear.Model.Data.lm$residuals^2),
  Function.Deviance=deviance(Linear.Model.Data.lm))
```

## 6. Akaike Information Criterion (aic)

```{r}
From.AIC.Function<-AIC(Linear.Model.Data.lm)
AIC.From.glm<-Linear.Model.Data.glm$aic
c(From.AIC.Function,AIC.From.glm)
```

```{r}
# Calculate AIC manually
Manual.Log.Likelihood<- function(Linear.Model.Fit)
```

```{r}
# Check 
(Log.Likelihood<-Manual.Log.Likelihood(Linear.Model.Data.lm))
```

## 7. Output y.

```{r}
sum(abs(Linear.Model.Data[,1]-Linear.Model.Data.glm$y))
```

## 8. null.deviance

```{r}
# Null deviance of glm() is the deviance of the null model, i.e. the model that has only intercept. Since deviance of glm() in case of family=gaussian(link="identity") is equivalent to SSE of lm() we need to estimate the null model with only intercept and calculate its SSE.
Linear.Model.Data.Null.lm<-lm(Output~1,data=Linear.Model.Data)
Linear.Model.Data.Null.lm.SSE<-sum(Linear.Model.Data.Null.lm$residuals^2)
c(Null.SSE.lm=Linear.Model.Data.Null.lm.SSE,Null.Deviance.glm=Linear.Model.Data.glm$null.deviance)
```

## 9. Dispersion.

```{r}

```

```{r}

```

```{r}

```

```{r}

```

























