---
title: "Week7_JianghongMan"
author: "Jianghong Man"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
datapath <- "/Users/nimo/Desktop/31007/7/HW7/"
Regression.ANOVA.Data<-
  read.csv(file=paste(datapath,"DataForRegressionANOVA.csv",sep="/"),
           header=TRUE,sep=",")
head(Regression.ANOVA.Data)
```

```{r}
fit.1<-lm(Output~1,data=Regression.ANOVA.Data)
fit.1.2<-lm(Output~1+Input1,data=Regression.ANOVA.Data)
fit.1.3<-lm(Output~1+Input2,data=Regression.ANOVA.Data)
fit.1.2.3<-lm(Output~.,data=Regression.ANOVA.Data)
```

```{r}
anova(fit.1.2)
```

```{r}
anova(fit.1.2)$Df
```

```{r}
anova(fit.1.2)$"Sum Sq"
```

```{r}
sum(fit.1.2$residuals^2)
```

```{r}
anova(fit.1.2)$"F value"[1]
```

```{r}
anova(fit.1.2)$"Pr(>F)"[1]
```

```{r}
summary(fit.1)
```

```{r}
anova(fit.1)
```

```{r}
c(anova(fit.1)$"Sum Sq",sum(fit.1$residuals^2))
```

```{r}
c(anova(fit.1)$Df,fit.1$df.residual,summary(fit.1)$df[2])
```

```{r}
test_dat <- read.table(paste(datapath,'Week7_Test_Sample.csv',sep = '/'), header=TRUE)
head(test_dat)
```

```{r}
test_dat_fit.1<-lm(Output~1,data=test_dat)
test_dat_fit.1.2<-lm(Output~1+Input1,data=test_dat)
test_dat_fit.1.3<-lm(Output~1+Input2,data=test_dat)
test_dat_fit.1.2.3<-lm(Output~.,data=test_dat)
```

```{r}
anova(test_dat_fit.1.2)$"Sum Sq"
```

```{r}
anova(test_dat_fit.1.3)$"Sum Sq"
```


```{r}
c(F.value=anova(fit.1.3)$"F value"[1],Df=anova(fit.1.3)$Df,P.value=anova(fit.1.3)$"Pr(>F)"[1])
```

```{r}
anova(test_dat_fit.1,test_dat_fit.1.2.3)
```
















