---
title: "Homework"
author: "Danny"
date: "September 1, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment='', results='hold', echo = TRUE)
```

# Question 1

## Importing the data

We import the [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) file using the `read.csv()` function.

```{r}
car <- read.csv("car.csv")
head(car)
```

## Summary Statistics

- The five-number summary includes:
    1. Miminum
    2. Lower quartile
    3. Median 
    4. Upper Quartile
    5. Maximum

```{r}
summary(car)
```

## Plot

To install the ggplot2 <https://ggplot2.tidyverse.org/> package, use the following code: 

```{r, eval=FALSE}
install.packages("ggplot2")
```

Below we fit a linear regression model of the form
$$MPG = \beta_0 + \beta_1 Horsepower$$.

```{r, echo=FALSE}
library(ggplot2)

ggplot(car, aes(Horsepower, MPG)) + # Start with a data frame.  Define the axes
  geom_point(aes(size = Weight), alpha=0.5, colour="orange") + # Add more graphic elements
  geom_smooth(method="lm", colour="steelblue2") +
  ggtitle("Relationship Between Horsepower and MPG")
```
